# Assignment Day 14-15

## Create a 3x3x3 array with random values

In [1]:

import numpy as np
x= np.random.random((3,3,3))
print(x)

[[[0.85242295 0.0052326  0.518735  ]
  [0.22144095 0.40633722 0.95126367]
  [0.45555302 0.45248253 0.0433782 ]]

 [[0.63843895 0.17011626 0.31074252]
  [0.99117616 0.71517084 0.51716585]
  [0.41293892 0.77837537 0.55721423]]

 [[0.82216365 0.35601712 0.0876602 ]
  [0.8672428  0.46775844 0.46495184]
  [0.19816525 0.39475561 0.7168616 ]]]


## Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
z= np.diag(1+np.arange(4),k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Normalize a 5x5 random matrix

In [4]:
a = np.random.random((5, 5))
a = a / np.linalg.norm(a)
a

array([[0.25429879, 0.05155975, 0.26897951, 0.24510049, 0.01802038],
       [0.09687884, 0.23525257, 0.32584248, 0.0151376 , 0.22874525],
       [0.08782582, 0.15423295, 0.11206318, 0.08742638, 0.05714285],
       [0.19079051, 0.28476989, 0.13916536, 0.13259372, 0.32217794],
       [0.14775728, 0.31530052, 0.33028429, 0.01590433, 0.18075311]])

## How to find common values between two arrays?

In [5]:
a1 = [1,2,4,5]
a2 = [1,4,8,6]
intersect = np.intersect1d(a1, a2)
intersect

array([1, 4])

## How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


## Consider two random array A and B, check if they are equal

In [7]:
A = np.random.rand(7)*10
B = np.random.rand(17)*10
print("A:", A)
print("B:", B)
print("Equal:", np.array_equal(A, B))

A: [4.11529625 2.65500072 1.24440419 2.02550508 5.48752052 2.59729287
 2.57346296]
B: [5.58577289 8.72553203 3.07277841 8.06993072 2.88187891 9.03879563
 7.51478297 1.03213977 8.81857406 2.45440407 9.0461282  9.06848685
 3.69995892 5.26649498 2.7416298  2.58151983 3.70486931]
Equal: False


## Create random vector of size 10 and replace the maximum value by 0

In [8]:
a = np.random.rand(10)*10
print("array Before:", a)
a[a.argmax()] = 0
print("array After:", a)

array Before: [0.81278452 2.5199845  0.28977542 3.31303411 1.93657754 1.33586281
 9.03077838 2.76078091 8.90676174 6.44208566]
array After: [0.81278452 2.5199845  0.28977542 3.31303411 1.93657754 1.33586281
 0.         2.76078091 8.90676174 6.44208566]


## How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=float("inf"))
a = np.random.random((10,10)) 
print(a)

[[0.45322911 0.46091974 0.63327136 0.41927281 0.80031443 0.05238963
  0.46419355 0.04061993 0.22942262 0.72870777]
 [0.2204512  0.74279774 0.94743864 0.51663813 0.78595845 0.17027545
  0.93355609 0.89693358 0.11021492 0.06796325]
 [0.62522877 0.17040887 0.01816962 0.6444744  0.89511451 0.28359581
  0.55420463 0.7821548  0.47089149 0.10136702]
 [0.18890135 0.54616544 0.61642653 0.14904303 0.66823974 0.44120895
  0.93956477 0.34404149 0.52657187 0.81364805]
 [0.71959829 0.33694211 0.18943039 0.4033268  0.35164021 0.23562696
  0.62367922 0.02882695 0.2551772  0.14162765]
 [0.61542997 0.70449344 0.76329393 0.58466063 0.46988256 0.53578735
  0.690754   0.84887315 0.3747303  0.94353743]
 [0.07238074 0.11828234 0.05114803 0.69362477 0.46184599 0.09820409
  0.14647414 0.11661287 0.71793803 0.62656612]
 [0.08774697 0.56311413 0.54466016 0.68737868 0.21911311 0.86951494
  0.44992132 0.67205535 0.90994067 0.73846133]
 [0.46237097 0.20469224 0.415037   0.18940514 0.11813915 0.67508507
  0.76079405

## Subtract the mean of each row of a matrix

In [10]:
print("before:\n")
a = np.random.randint(1, 10, (4,4))
print(a)
mean =a.mean(axis=1)
print('\nmean of each row',mean)
print("\nafter subtracting mean:\n")
a1 = a - mean
print(a1)

before:

[[4 5 5 6]
 [6 4 6 5]
 [7 9 1 1]
 [5 3 1 7]]

mean of each row [5.   5.25 4.5  4.  ]

after subtracting mean:

[[-1.   -0.25  0.5   2.  ]
 [ 1.   -1.25  1.5   1.  ]
 [ 2.    3.75 -3.5  -3.  ]
 [ 0.   -2.25 -3.5   3.  ]]


##  Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
a = np.ones(10)
print('vector before addition\n',a) 
index =[1,3,5,7,9,1]
print('\nindex vector\n',index) 
np.add.at(a, index, 1)
print('\nvector before addition\n',a)

vector before addition
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

index vector
 [1, 3, 5, 7, 9, 1]

vector before addition
 [1. 3. 1. 2. 1. 2. 1. 2. 1. 2.]


## How to get the diagonal of a dot product?

In [12]:
A = np.array([[1, 2], [4, 3]])
B = np.array([[1, 2], [4, 3]])
print(A)
print(B)

np.diag(np.dot(A, B))

[[1 2]
 [4 3]]
[[1 2]
 [4 3]]


array([ 9, 17])

## How to find the most frequent value in an array?

In [13]:
a = np.random.randint(0,10,10)
print (a)
most = np.bincount(a).argmax()
print('Most Frequent Value:' , most)

[2 7 3 1 8 4 5 2 4 2]
Most Frequent Value: 2


## How to get the n largest values of an array

In [14]:
a = np.random.randint(3, 50, 10)
print('array')
print(a)
n = 3
nlargest = a[(-a).argsort()[:n]]
print('n-largest')
print(nlargest)

array
[32 26 16 29 28 31 20 28 31 21]
n-largest
[32 31 31]


## How to create a record array from a regular array?

In [15]:
a=np.array([(101, 'Jitender', 21),(102, 'Deepak', 20)])
gfg = np.core.records.fromrecords(a.T,names = 'Rollno, Name, Age') 
gfg

rec.array([('101', '102'), ('Jitender', 'Deepak'), ('21', '20')],
          dtype=[('Rollno', '<U8'), ('Name', '<U6')])